name: Auto-Approve Renovate
on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: ✅ approve renovate pull request
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
